model_id = "Qwen/Qwen2.5-0.5B-Instruct"
n_layers = 24
hidden_size = 896
supports_tensor = false
tasks = ["TextGeneration"]
family = "qwen"
quantization = ""
base_model = "Qwen2.5 0.5B"
capabilities = ["text"]

[storage_size]
in_bytes = 494000000
